### ISSUE TITLE
Build on Ubuntu 16.04

### ISSUE THREAD

**Issue by vahid-dan** [sutanay/PbCdlComm#1]
Hi;

I'm trying to build it on Ubuntu 16.04 with `gcc version 5.4.0`. But, it throws multiple errors. It seems some packages are depreciated, and it is not easy to solve them one by one. Have you ever build it on Ubuntu 16.04? Any suggestions?

Thanks,
Vahid

**Comment by sutanay** [comment]
Sorry Vahid – I have not build this in a while.  I checked with a colleague of mine, who last build that on gcc 4.4.7 – going from gcc 4.x.x to gcc 5.x.x probably made major changes.

Please consider contributing the patches if you can fix this problem.

Sutanay

**Comment by vahid-dan** [comment]
Hi Sutanay;

I just successfully built and installed PbCdlComm on Ubuntu 16.04 and sent a pull request.

Thanks for your fantastic software!

Bests,
Vahid
